title: 'Alessandro Santos - Portfolio'

# O e-mail do portfólio (comentado)
email: alessandro.siga@gmail.com

# Descrição do portfólio (comentada)
# description: >-
This is my professional portfolio where I showcase my data engineering projects and skills.

# URL base do seu portfólio
url: 'https://github.com/santospage/santospage.github.io'

# Definindo o tema do site
theme: minima

# Adiciona a linha para incluir seu arquivo CSS personalizado
sass:
  sass_dir: _sass

# URL base do seu site (em caso de hospedagem em subdiretório)
baseurl: ''

# Plugins do Jekyll
plugins:
  - jekyll-feed
